### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by t-bltg**
- make default `width` and `aspect ratio` references (avoids hard-coding constants);
- rename `TERM_DEBUG_ON` to `DEBUG_ON`, defaults to false for the end user;
- `term_theme` is now uppercase (consistency with globals naming conventions);
- `grid` is now exported;
- rename `int` to `rint` (`int` is confusing), to go with `fint` and `cint`;
- add `Measures.default_size()` to avoid hard-coded placeholder size;
- `calc_nrows_ncols` now defaults to `aspect = nothing` and is more clever for fitting (takes best layout between unit ar and default ar, which is set to `4:3`, in order to avoid placeholders);
- rewrite `runtests.jl` for clarity and flexibility;
- better `09_test_layout.jl` testing;
- a few syntax / cosmetic fixes;
- improve coverage.

 I think it `4:3` is the best choice since terminals seem to respect a `4:3` aspect ratio.

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Looks great again! Awesome work.
What's `.default_size() ` for?

**Comment by t-bltg** [comment]
>  What's .default_size() for?

It's used to compute the default `PlaceHolder` size when using `grid` without any renderables.

Aside from this,

`style_sub_types` and `style_super_types` in `src/_inspect.jl` seem unused and I can't find an example how to use these (for testing / coverage): do you have an example, or should we remove these if obsolete ?

**Comment by FedeClaudi** [comment]
you're right they're obsolete. They were used by the older `inspect` function but this has now been replaced by the much improved `termshow` - they can go 👋🏻

**Comment by FedeClaudi** [comment]
good to merge?

**Comment by t-bltg** [comment]
Yes.

**Pull request merged**
