### PR TITLE
support `:NONE` box borders

### PR DESCRIPTION
**Pull request by t-bltg**
I'd like to be able to use the layout features of `Term.jl` without printing panel borders.

Simple use case:
```julia
julia> using UnicodePlots, Term
julia> panel(p; kw...) = Panel(string(p, color=true); fit=true, box=:NONE, kw...)
julia> panel(lineplot(1:4, canvas=DotCanvas)) * panel(scatterplot(1:4, canvas=DotCanvas)) |> print
                                                                                                            
        ┌────────────────────────────────────────┐            ┌────────────────────────────────────────┐    
      4 │                                     ..'│          4 │                                       '│    
        │                                   .'   │            │                                        │    
        │                                .''     │            │                                        │    
        │                             ..'        │            │                                        │    
        │                           .'           │            │                                        │    
        │                        ..'             │            │                          '             │    
        │                      .'                │            │                                        │    
        │                   .''                  │            │                                        │    
        │                ..'                     │            │                                        │    
        │              .'                        │            │                                        │    
        │           ..'                          │            │             '                          │    
        │         .'                             │            │                                        │    
        │      .''                               │            │                                        │    
        │   ..'                                  │            │                                        │    
      1 │..'                                     │          1 │.                                       │    
        └────────────────────────────────────────┘            └────────────────────────────────────────┘    
         1                                      4              1                                      4     
                                                                                                          
```

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Hey, 

Thanks for the PR, but I'm not sure if this would be useful to have for a couple reasons:

1. Layout in `Term` works with any renderable, not just `Panel`. So the following does what you need:
```Julia
using Term, UnicodePlots
import Term: Renderable

p1, p2 = lineplot(1:4, canvas=DotCanvas), scatterplot(1:4, canvas=DotCanvas)
print(Renderable(string(p1)) * Renderable(string(p2)))
```

2. You can do something like `Panel(...; style="hidden")` this creates a panel whose border is not displayed using ANSI codes. This doesn't work in every terminal but it should in most. That's how `TextBox` works in Term.

The only advantage I can see with your approach is that you get `Panel`'s capability in terms title/subtitle, padding etc... without showing the border and without having to rely on a terminal parsing the ANSI correctly. I guess that's a good reason?


By the way, from the next release Term's renderables will display automatically in the REPL like your plots do, so that should make rapid prototyping of the layouts much faster since you don't need to print stuff. Also there will be additional functionality to left/center/right align renderables.

**Comment by t-bltg** [comment]
> You can do something like Panel(...; style="hidden")

Thanks, 2) is the solution to the initial issue.

1) is not satisfactory, because I need the columns to be aligned when using multiple rows, hence the `fit` kw from `Panel`s.

**Comment by FedeClaudi** [comment]
That's fair. The next release will have improved layout functionality: https://github.com/FedeClaudi/Term.jl/issues/91#issuecomment-1140301546 but still using panels helps. 

I do like your solution though, it avoids having to go through the ANSI stuff which might work better especially with older terminals and on windows. I think I'll merge if that's okay with you!

**Comment by t-bltg** [comment]
> I think I'll merge if that's okay with you!

Do as you wish :D. Is it normal that the tests are broken on master ?

**Comment by FedeClaudi** [comment]
it's not, but I had fixed them on the development branch and was waiting to merge those (before breaking them again, lots of changes lately). I'll merge this and handle the tests in a few days, thanks for the contribution.

**Pull request merged**
