### PR TITLE
remove `console_width` calls from `Base...` methods - add `UnicodePlots` test

### PR DESCRIPTION
**Pull request by t-bltg**
`console_width()` depends on a global state by calling `displaysize()`, hence this leads to non-reproducible `Term` output.
As a fix, I've removed `console_width` call from `Base....` methods calls [1].

~~I've reworked the `fit` logic, as it seemed unclear: `fit = nothing` now stands for `auto` using `console_width()`, whereas using a boolean `true` or `false` forces fitting (to be discussed ?)~~.

EDIT: actually, only the changes mentioned in [1] are necessary to fix this issue, and the tests are passing.

Fix https://github.com/FedeClaudi/Term.jl/issues/160.

### CODE REVIEW

**Comment by t-bltg** [comment]
Un-necessary padding occurs when `style="hidden"` is used, so I've fixed this.

Rationale: `UnicodePlots` layout examples in https://github.com/JuliaPlots/UnicodePlots.jl#layout..

**Comment by FedeClaudi** [comment]
Looks good, thank you very much for working on this. 

Would a new release help making these changes available to terminal plots users?

**Comment by t-bltg** [comment]
Thanks. Yes, a new release would be appreciated, especially for the `console_width` fix since it cripples plots atm in tests.

**Comment by FedeClaudi** [comment]
okay, on it

**Comment by t-bltg** [comment]
Many thanks.

**Pull request merged**
