### PR TITLE
Theme functionality improvements

### PR DESCRIPTION
**Pull request by FedeClaudi**
Following on https://github.com/FedeClaudi/Term.jl/issues/156 (cc [goerz](https://github.com/goerz)).

Made `Theme` more comprehensive so that it can be used to alter the colors of virtually everything. 
Next step: add a few default themes (e.g. for light backgrounds).

@goerz would you be interested in volunteering a theme for light backgrounds? I don't really use so maybe someone with more experience can come up with something better.

### CODE REVIEW

**Comment by FedeClaudi** [comment]
image

**Comment by goerz** [comment]
Wow! That's awesome

I'll definitely have a look this...

**Comment by goerz** [comment]
One thing that would really help with theme development in general (and a light theme in particular) is to wrap some variation of the [`Readme.jl` script](https://github.com/FedeClaudi/Term.jl/blob/master/README.jl) in a `demo()` function. That variation should

1. Not have a lot of custom colors/styling. The current `README.jl` has a lot of those, which if fine of course for showing things off in the actual `README`.
2. make sure to hit *all* of the theme attributes (`name`, `docstring`, `string`, ...) in some realistic context.

Maybe take a `theme` as an argument to `demo` so that it's easy to run for different themes, and maybe also have has `annotate` flag that would either replace texts with the the name of the theme attribute that's rendering that text, or append the attribute name to the text so that it's immediately clear which attribute one would have to change. So, something like `demo(theme=<default>; annotate=false)`

**Comment by FedeClaudi** [comment]
Good idea @goerz.
I've added a `demo` function that displays most things that get affected by a `Theme` (not all, e.g. can't display error stack traces). 
It doesn't explain much, but it at least allows you to see the effects of changing a theme. I think a more detailed explanation of what each entry in `Theme` affects is better left to the docs.

**Comment by FedeClaudi** [comment]
In the future perhaps a live renderable (https://github.com/FedeClaudi/Term.jl/pull/152) can be used to showcase different themes interactively

**Comment by goerz** [comment]
> I've added a `demo` function that displays most things that get affected by a `Theme` (not all, e.g. can't display error stack traces).

Super helpful. I've started a light-background colorscheme at https://gist.github.com/goerz/4fa0df627696452ef698a0c15ee0dc2b. This is still WIP.

The "logging" section doesn't seem to have any effect — which is strange, because the code sure looks like it's taking colors from the scheme.

**Comment by FedeClaudi** [comment]
So I'm sure you're already doing this but you need `install_term_logger`, `install_term_stacktrace` and `install_term_repr` to see some of the effects.

For the logging specifically, [`TermLogger`](https://github.com/FedeClaudi/Term.jl/blob/19ef3845d60897a704377107dded0929b759a313/src/logs.jl#L51) is passed an instance of `Theme` which then it uses when creating the log output. So if you change `TERM_THEME` after having created the logger you won't see changes, you'd need to create a new logger.

This is perhaps not ideal? It's a leftover from the fact that I wrote the logging stuff before I had a proper `Theme` system in place.

**Comment by FedeClaudi** [comment]
Hey @goerz , 

I ended up getting swamped with other things.. Still interested in working on this together? I think it should be mostly ready.

**Pull request merged**
