### PR TITLE
precompile

### PR DESCRIPTION
**Pull request by FedeClaudi**
@VarLad I've opened this to discuss https://github.com/FedeClaudi/Term.jl/issues/141

This is a branch from `master` while before I was testing the development branch for the up-coming version, I thought this might make things easier. 

BEFORE using snoopcompile
image

AFTER
image

### CODE REVIEW

**Comment by VarLad** [comment]
@FedeClaudi Also, in your "AFTER", notice that you're including the Precompile time with the compile time. 
I'd recommend to close the Julia session after your first `using Term` and then do 
```
@time using Term
@time Panel("test")
```
again

**Comment by FedeClaudi** [comment]
I see what you mean, the first time `using Term` is called its a bit slower but after that it loads faster for future sessions, neat.

> Which is appropriate (it increases the precompile time, doubles the load time, but reduces the execution time)

I guess what I'm confused about is that despite precompilation `@time Panel()` shows that some compilation is still done:
```julia

julia> @time using Term
  0.391873 seconds (815.66 k allocations: 54.100 MiB, 2.91% compilation time: 85% of which was recompilation)

julia> @time Panel()
  0.081357 seconds (6.94 k allocations: 322.232 KiB, 99.33% compilation time)
╭──────────────────────────────────────────────────────────────────────────────────────╮
╰──────────────────────────────────────────────────────────────────────────────────────╯


julia> @time Panel()
  0.000223 seconds (338 allocations: 22.773 KiB)
╭──────────────────────────────────────────────────────────────────────────────────────╮
╰──────────────────────────────────────────────────────────────────────────────────────╯
```

Not that it makes a huge difference, but I would've thought that the first `@time Panel()` would be the same as the second since `Panel()` should be pre-compiled?

**Comment by VarLad** [comment]
@FedeClaudi 
> Not that it makes a huge difference, but I would've thought that the first @time Panel() would be the same as the second since Panel() should be pre-compiled?

We can't precompile _everything_ :P 
Also, I tried direct precompilation (without the SnoopPrecompile lines)
```julia
if ccall(:jl_generating_output, Cint, ()) == 1   # if we're precompiling the package
    let
        Panel()
        Panel("test") * Panel(Panel()) / hLine(20) |> tprint
        Panel(Panel("Text"))
    end
end
```
just before the module ends.
The results are similar-ish.

Whats concerning though is, I see that there is a lot of cache invalidation, which triggers recompilation. (for example with `Panel("Some text")` I believe this can be avoided with changes in the package itself, and lowering the invalidation where possible will make the entire package more usable.
https://timholy.github.io/SnoopCompile.jl/dev/snoopr/#invalidations
I think this is going to take more time and term effort, but it certainly looks doable. I'd recommend to keep the draft open for now.

**Comment by FedeClaudi** [comment]
Thank you! Precompilation and TTX is one of the areas of Julia I haven't digged into yet. Input from Term's users that want to improve the package is always the best motivation to get me to do things!

> I'll look into whats specifically causing the invalidations with more time. :D

That would be great! I will also look into stuff, but I first need to learn a bit more about pre-compilation,methods invalidation etc... any help would be great. 

P.s.: term is not very type stable at all, would that make pre-compilation less effective?

**Comment by VarLad** [comment]
> P.s.: term is not very type stable at all, would that make pre-compilation less effective?

I think that would contribute to the problems, yes. 
I'd recommend into looking into https://timholy.github.io/SnoopCompile.jl/dev/ . The docs have a lot of good points and have a few tools to help you make your package faster. :D

**Comment by FedeClaudi** [comment]
As fully optimizing TTX will be a more involved project, I will merge this for now and leave the issue open as a reminder for when I will have the time. This will already help a little bit, I will release a new version today/tomorrow with this precompilation bit if you want to get it.

**Pull request merged**
