### PR TITLE
Make testing more robust on wide term size

### PR DESCRIPTION
**Pull request by t-bltg**
- fix https://github.com/FedeClaudi/Term.jl/issues/112 (added comments in tests);
- change `testpanel` and `testtree` function to macros, for better stacktrace when erroring;
- rename `truncate` to `str_trunc` (since it shadows a builtin function, not a good idea);
- swap remaining `(w, h)` in tests;

Fixes https://github.com/FedeClaudi/Term.jl/issues/112.

I've changed the `"."^500` to `"°"^500` instead in the panel tests because it initially got me confused with the added trailing dots `...` when truncating the panel content.

@FedeClaudi, good to merge when green.

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Hey, 

Finally had time to look into this. It looks good! 
Why did you mark it as draft? I'm happy to merge when you are, I'll try to release v1.0 today. 

Also, I think you've seen it but look at UnicodePlots and Term working together! https://twitter.com/mdcatchen/status/1537915624575209475?s=20&t=1Zl9bveIZlUyS7OF4FiJDQ

**Comment by t-bltg** [comment]
> Why did you mark it as draft? 

I was reworking the grid slightly to accept a `NamedTuple` and use it's keys in the layout expression.

**Comment by t-bltg** [comment]
I have a question regarding the colors used in `Term.jl`: it seems you are a bit re-inventing the wheel. Why no re-use the exhaustive `Colors.jl` or one of the numerous existing packages ?

E.g. using a `style = "darker_red"` does not work currently and requires https://github.com/FedeClaudi/MyterialColors.jl/pull/7.

Also where did you get `CODES_16BIT_COLORS` or `COLORS_16b` from `Term.jl/src/_ansi.jl` ? It might be worth adding the sources / references...

**Comment by FedeClaudi** [comment]
Hey, 

The colors lists for 8/16 bits colors are fairly standard: [wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors), but I got the ones used here from rich: https://github.com/Textualize/rich/blob/master/rich/color.py

> I have a question regarding the colors used in Term.jl: it seems you are a bit re-inventing the wheel. Why no re-use the exhaustive Colors.jl or one of the numerous existing packages ?

In part to have fewer dependencies for packages that seem to do a lot more. In part because functions like:
https://github.com/FedeClaudi/Term.jl/blob/72f1d23d7b163f229b5005b0a39f4e502ae126c4/src/colors.jl#L135
would still need to be there (e.g. to deal with background colors).  
I'm guessing the main advantage would be the `hex -> rgb` conversion? But that's just a few lines I don't think it warrants having an additional dependency. 


> using a `style = "darker_red" `does not work 

It doesn't because the colors in `MyterialColors` are not standard named colors (the 8/16bit colors listed above) They are nice colors that I use frequently so I made a package to store the hex codes to avoid having to remember/look up. Otherwise only 8/16 bit named colors are picked up from strings.

**Comment by FedeClaudi** [comment]
https://github.com/FedeClaudi/MyterialColors.jl/pull/7

I'm confused about how this helps? You've improved how the codes are defined and removed some exported colors, but I don't see why `style="red_darker" would work after that?

**Comment by t-bltg** [comment]
> 8/16 bits colors

I guess we're talking about 8-bit colors and 24-bit colors (true color, 1 byte = 8 bits per channel, for `R, G & B`) ?

> In part to have fewer dependencies for packages that seem to do a lot more.

I see.

> I got the ones used here from rich

Thanks.

> removed some exported colors

No, I re-exported them https://github.com/FedeClaudi/MyterialColors.jl/pull/7/files#diff-1a9b9d7673a79fd4abb7a34d0effc0efe76c016905a16c1cf39277b6d790d913R123.

> I don't see why `style="red_darker" would work after that

It's hidden in this PR: https://github.com/FedeClaudi/Term.jl/pull/114/files#diff-b29208680d97c8a77bc9060b3377d8d0ee4180f2a48bbe1a8210292504128a1cR146.

**Comment by FedeClaudi** [comment]
I see, got it thanks. Good addition with directly parsing the MyterialColors colors. I don't think users would take advantage of this (I suspect they'll use their own favourite colors/names), but it can be convenient internally so that we don't have to have variables holding the color names.  
Do you know if getting the value out the dict everytime would be slower/more allocating?

**Comment by t-bltg** [comment]
>  I don't think users would take advantage of this

I can remove that, and use more standard color names.

> https://github.com/Textualize/rich/blob/master/rich/color.py

I think copying this table is not a good idea: I doubt anyone will use `sea_green2` directly, and we could maybe use default named W3 html colors https://www.w3schools.com/colors/colors_hex.asp](https://www.w3schools.com/colors/colors_names.asp). Then we could map names to `24` bit color codes directly for hex values (https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit).

Did you consider using `Crayons.jl` (we use it in `UnicodePlots` for handling colors) ?

>  Do you know if getting the value out the dict everytime would be slower/more allocating?

Better use a `NamedTuple` since it's non mutable.

**Comment by t-bltg** [comment]
@FedeClaudi, let's merge this PR, and change discuss colors in another PR.

**Comment by FedeClaudi** [comment]
Okay. 

I didn't look into `Crayons.jl`, but let's table that for another discussion (a PR or a Discussion)

**Comment by t-bltg** [comment]
For reference, I did the transition `8bit` -> `24bit` for capable terminals in https://github.com/JuliaPlots/UnicodePlots.jl/pull/238, and it was far from easy :laughing: .

**Comment by FedeClaudi** [comment]
it should be the same colors listed in Term? Just as RGB instead of the ANSI code for the named color.

**Comment by t-bltg** [comment]
It seems the names differ. Also, you loose information when using ansi color codes (8 bit) over true `RGB` colors.

You can merge this PR now and I'll open another one.

**Comment by FedeClaudi** [comment]
Okay, if you think that it;s worth it we can look into adding Crayons.

**Comment by t-bltg** [comment]
Well at least it unifies `Term` and `UnicodePlots`, and it allows you to toggle easily between `8bit` and `24bit` colors.

It also depends if you are ready to drop `MyterialColors` and rework the colors (I don't want to impose anything, but working with colors can be hard, and it's always better to use the same conventions, regarding that matter).

That being said, it's going to be a mess, and breaking. But I can do that now.

**Comment by FedeClaudi** [comment]
I'll be honest, I think what you're saying makes a lot of sense, and it would be great to have. 
That said, I don't think rn I have the time/motivation to do it, but at the same time I don't want to impose this (seemingly annoying) task on you either. So if you want to table it as just a discussion for something to implement in the future I'm happy with that.

**Comment by t-bltg** [comment]
I started something in https://github.com/t-bltg/Term.jl/tree/cols, but it requires a lot more thinking to support `Crayons`.

What I really like about `Crayons` is that [parsing colors is type dependent](https://github.com/KristofferC/Crayons.jl/blob/417e3af6f3c28168553c662f605255b8e1fe1f14/src/crayon.jl#L139), which is very julian and neat IMO:
- `UInt32` -> 24bits, truecolor (see https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit);
- `Symbol` -> 3, 4bits system, terminal dependent (16 colors, see https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit);
- `Integer` -> 8bits (a.k.a. color cube, see https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit);
- `NTuple{3,Integer}` 24bits, parsed as rgb channels.

I don't know if we can integrate this in `Term.jl` easily.

**Comment by FedeClaudi** [comment]
I'm not sure either! I'd have to look into `crayons` more... 

If there's an easy way to use it to go from strings to ANSI codes it should be fine. The `symbol/number -> color` conversion here, although nice, is less relevant for term. Term's `markup` syntax should be mostly string based so that it can be interpolated in normal text strings with no fusses. You could still recover the type under the hood and use that for the colors conversions, ofc.

**Pull request merged**
