### PR TITLE
Remove `AbstractRenderable` restriction on argument types

### PR DESCRIPTION
**Pull request by t-bltg**
There is no reason to restrict `grid` to a vector of `AbstractRenderable`s.
Fix another forgotten swap in `calc_nrows_ncols`.

Usage:
```julia
# remove restriction on these common patterns vvv
p = Any[]
# ...
  # push in some kind of loop
  push!(p, Panel())
# ...
grid(p)
```

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Nice, but that removes the options to pass no renderables (`nothing`)?
Perhaps we can split that into a separate method for `grid`?

**Comment by t-bltg** [comment]
> Nice, but that removes the options to pass no renderables (nothing)

No, this was already split in https://github.com/FedeClaudi/Term.jl/pull/113 (see https://github.com/FedeClaudi/Term.jl/blob/master/src/grid.jl#L89).

I've however, added more tests.

**Comment by FedeClaudi** [comment]
Ah nice I had missed that.  Happy to merge when you're ready.

**Comment by t-bltg** [comment]
You can merge ;)

**Pull request merged**
