### PR TITLE
WIP - v1.0.0

### PR DESCRIPTION
**Pull request by FedeClaudi**
Work in progress..

Changes:
- changed markup syntax from `[...]` to `{...}`
- new layout syntax to align/stack renderables
- `@with_repr` and `install_term_repr`
- improved threading in progress bar display
- improved string highlighting and added to `tprint`
- refactored/improved errors and logging code
- custom `Theme` support

In progress
- `grid`: https://github.com/FedeClaudi/Term.jl/pull/101
-  [x] merge formatting from `grid` PR
- [x] Table - finish code
- [x] non-destructive layout workflow

To do:
- Add tests for new functionality
- Update docs + new functionality

### CODE REVIEW

**Comment by t-bltg** [comment]
As a side note, considering the number of breaking changes introduced in https://github.com/FedeClaudi/Term.jl/pull/101, I think it should be released as `1.0.0` instead of `0.4.0` according to semver :wink:

**Comment by FedeClaudi** [comment]
@johnnychen94  an update on the multi-renderable layout discussed here: https://github.com/FedeClaudi/Term.jl/pull/101#issuecomment-1140968184

There's now a `Compositor` that accepts an `Expr` specifying a layout. The Layout expression uses symbols for names of different elements and `(w, h)` for their size:
```julia
layout = :(A(50, 10) * B(50, 10))
compositor = Compositor(layout; hpad=3, vpad=1)
```

the `Compositor` parses this and creates place holders of the appropriate shape and lays them out as described in the `layout` expression (note the `*`):
image

you can then go and change individual elements of the composition:
```julia
compositor.elements[:B].renderable = Panel(; width=50, height=10)  # the size needs to match what we specified for :B
```
image


This is particularly powerful since you can use the full layout "syntax" (`vstack, lvstack..`) and use padding too to create complex layouts:
```julia
layout = :(
    rvstack(
        (A(25, 5)/B(25, 5)), C(50, 5); pad=2) * D(25, 19) * lvstack(
            E(25, 5), F(25, 5), G(50, 5); pad=1
    )
) 
```
image

The fact that it creates these placeholders for you means you can rapidly prototype the layout without having to mess around with its contents.  The other main advantage is that you can interactively change the "content" without having to worry about the layout any-longer. So if you iteratively clear out the console and print the `compositor` with updated renderables you can make something with a live update. This (a bit contrived) shows it:
```julia
using Term
import Term.Compositors: Compositor
import Term.Repr: termshow
import Term.Layout: vstack
import Term.Console: clear
import Term.Tables: Table
using Term.Boxes

using UnicodePlots
import MyterialColors: Palette, blue, pink


boxes = [
    :SQUARE, :SQUARE_DOUBLE_HEAD, :MINIMAL, :MINIMAL_HEAVY_HEAD,
    :HEAVY_EDGE, :HEAVY_HEAD, :DOUBLE, :DOUBLE_EDGE,
    :SIMPLE, :SIMPLE_HEAD
]
colors = getfield.(Palette(blue, pink; N=10).colors, :string)


layout = :((A(50, 15) * B(50, 15)) / C(103, 10))
compositor = Compositor(layout; hpad=3, vpad=1)

for i in 1:10
    X = rand(5, 2)

    _plot = Panel(
        string(
            scatterplot(X[:, 1], X[:, 2], title="{red}My Scatterplot{/red}", width=30, height=8)
        ); width=50, height=15, box=:NONE
        )

    _lineplot = string(
            lineplot(rand(100), title="{blue}My lineplot{/blue}", width=95, height=8)
        )
    

    data_table = Table(round.(X, digits=3); 
                header = ["X", "Y"],
                style=colors[i],
                header_style="bold green", 
                box=boxes[i])

    _data = Panel(data_table; width=50, height=10, justify=:center, padding=(2, 2, 0, 0), 
                style="red dim", box=:HEAVY, title="Data table", title_style="default red bold")


    compositor.elements[:A].renderable = _plot
    compositor.elements[:B].renderable = _data
    compositor.elements[:C].renderable = _lineplot
    clear()
    print(compositor)
    sleep(.25)
end
```

https://user-images.githubusercontent.com/17436313/171287714-75b3c5b6-45c3-475b-80a0-e745fddcc2c5.mov



Still some bugs to fix and a few quality of life improvements, but I like where this is going!

**Comment by t-bltg** [comment]
Wow, I'm very impressed with the recent improvements :clap: .

Here are a few general comments:

Are you familiar with the julian syntax:
```julia
a = if something
    [1]
else
    nothing
end
```
instead of :
```julia
if something
    a = [1]
else
    a = nothing
end
```
? It saves a few chars and avoids repetition.

Regarding the new compositor, using `Expr` is very powerful. Should we implement auto layout (with a layout keyword) as I tried when defining `grid` or should we use `Table` as  you suggested in https://github.com/FedeClaudi/Term.jl/pull/101#issuecomment-1141425872 ?

I'd like to be able to use `display(compositor)` (high level) instead of `println(compositor)` (low level, should be debug or repr ?).

Shouldn't we use an `OrderedDict` for the compositor `elements` ? I think it should retain insertion order (julia `Dict` are **not** ordered), so that `update!` can be called using the same `Expr` sequence.

I guess `Compositor` (and maybe `update!` ?) should be exported by `Term.jl`.

Some minimalist example I'd wish for:
```julia
using UnicodePlots, Term

panel(p; kw...) = Panel(p isa String ? p : string(p, color=true); fit=true, style="hidden", kw...)

plots = collect(
  panel(lineplot(1:2, width=20, height=10, color=c))
  for c in (:red, :green, :blue)
)

compositor = Compositor(plots; hpad=3, vpad=1, layout=(1, 5))  # auto-layout, should insert hidden placeholders auto-magically

display(compositor)
```

**Comment by FedeClaudi** [comment]
I didn't know that syntax! I've been using `a ? b : c` for simple expressions but not for multi-lines expression. I like that!

Thanks for the comments, let me try to address them:
> Regarding the new compositor, using Expr is very powerful.

Indeed, though I would eventually like to support matplotlib's [string layout syntax](https://matplotlib.org/3.5.0/tutorials/provisional/mosaic.html#string-short-hand) as it's more intuitive, the expression syntax is more powerful. 

> I'd like to be able to use display(compositor) (high level) instead of println(compositor) (low level, should be debug or repr ?).

Okay, it can have the same behavior as the renderables. 

> Shouldn't we use an OrderedDict for the compositor elements ? I think it should retain insertion order (julia Dict are not ordered), so that update! can be called using the same Expr sequence.

I'm not sure what you mean at the end?
```julia
update!(compositor, :A, Panel(; width=50, height=15))
```

`update!` specifically names the compositor element to update, it doesn't need the layout Expr? `update!` updates the content of the Compositor, it doesn't trigger its rendering. At render time the compositor uses the stored layout expression to render whatever content is available.  We can use `OrderedDict` but I'm not sure what the benefit would be here?


> Should we implement auto layout (with a layout keyword) as I tried when defining grid or should we use Table as you suggested in https://github.com/FedeClaudi/Term.jl/pull/101#issuecomment-1141425872 ?

`Compositor` is different from the `AbstractRenderables` like `Panel` in Term - indeed it's not a renderable. That means it can't be used for layout with other renderables (`compositor / panel` won't work). There's pros and cons for this choice, but the main reason is that it works differently since you can update it's content at will and in a modular way, so I think it should be a different kind of object (though a `Renderable(compositor)` method sould probably be available. 

So I think it would still be good to have a `Grid` renderable which builds upon `Table` to create a standard renderable. At the same time it would be nice to have `Compositor(plots; hpad=3, vpad=1, layout=(1, 5)) ` as an option too. There might be a bit of overlap there but I think it's best to have both things as separte options:
1. if you want a renderable, use `Grid` - can't do fancy layouts like compositor
2. if you want a fancy layout + renderable: `Renderable(compositor)`
3. if you want something that eats renderables and you can update piece meal use `compositor`.

Perhaps the `Grid` layout could be built through `Renderable(compositor)`, but at that point I think `Table` makes more sense (also it lets you add headings). 


Sorry for the wordy reply, but I guess my thoughts on the matter are not 100% clear so I just wanted to lay them out and get your feedback since it's been so helpful!

**Comment by t-bltg** [comment]
I won't have time to work on it before the end of the week, so you can go ahead by taking the code that was removed from https://github.com/FedeClaudi/Term.jl/pull/101.

I'd be happy to review when ready, and add test scenarios though before the final merge !

**Comment by FedeClaudi** [comment]
Got distracted with the markdown parser, but adding the `grid` functionality now. Adding some edge cases where the behavior is not what I'd expect.

```
import Term.Layout: grid, PlaceHolder

rens = repeat([PlaceHolder(10, 5)], 9)
grid(rens; pad=(2, 1), aspect= 1.5, placeholder=PlaceHolder(10, 5; style="red"))
```
image

**Comment by lorenzoh** [comment]
Really looking forward to these updates!

I've been playing around with iterator wrappers that create nested progress bars and just updated to this branch, but am now not getting any progress bars printed, e.g. in the following example, no progress bar is shown:

```julia

pbar = ProgressBar()
job = addjob!(pbar; N = 100)
start!(pbar)
for i in 1:100
    update!(job)
    sleep(0.03)
    i % 25 == 0 && println("We can print from here too")
end
stop!(pbar)
```

If you're already aware of this, please ignore my comment 😅

**Comment by FedeClaudi** [comment]
HI Lorenzo, 

Thanks for trying out the newer version. The way progress bars work has changed a bit so that a `sleep` statement is not necessary any longer (previously you needed one in the loop to ensure that the progress bar would be rendered, now it happens in a separate thread).
As a consequence you need to call `render` on the progress bar:
```julia
using Term.Progress

pbar = ProgressBar()
job = addjob!(pbar; N = 100)
start!(pbar)
for i in 1:100
    update!(job)
    sleep(0.03)
    i % 25 == 0 && println("We can print from here too")
    render(pbar)
end
stop!(pbar)
```

Note that if you use `@track` or `with` you don't need `start!, stop!` and `render`. These are the recomended ways to use the progress bars since they're more robusts to errors during the progress bar display (also they're more convenient):

```julia


pbar = ProgressBar()
job = addjob!(pbar; N = 100)
with(pbar) do
    for i in 1:100
        sleep(0.03)  # only needed to slow down the display
        i % 25 == 0 && println("We can print from here too")
        update!(job)
    end
end
```

Let me know if it works and if you have any other question or problem!

**Comment by FedeClaudi** [comment]
@t-bltg I think this is pretty much ready to merge in master. The tests could be made a bit more thorough, but otherwise the functionality I wanted to have for the next release is there - when we merge I can start working on the docs update. Let me know what you think!

**Comment by lorenzoh** [comment]
Hey Federico, thanks for the quick response!

Unfortunately, I can't use `with` as I'm writing a wrapper for iterators (e.g. `for x in withprogress([1, 2, 3]); ...; end`) and I need to keep the progress bar alive while the loop body is running and only stop it once the loop has finished. I'll look at the source code of `with` to see how to do that safely 👍

**Comment by FedeClaudi** [comment]
I see. That's a use case that I would like for Term to be able to handle, if you come up with a good solution perhaps you can contribute a PR?

**Comment by t-bltg** [comment]
> @t-bltg I think this is pretty much ready to merge in master.

Am trying to review this, but the test don't pass locally:

<details>
  <summary><strong>details</strong></summary>

```julia
PANEL - FIT - measure: Test Failed at [...]/Term.jl/test/__test_utils.jl:69
  Expression: length(unique(widths)) == 1
   Evaluated: 2 == 1
Stacktrace:
 [1] macro expansion
   @ [...]/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] testpanel(p::Panel, w::Int64, h::Nothing)
   @ Main [...]/Term.jl/test/__test_utils.jl:69
PANEL - FIT - measure: Test Failed at [...]/Term.jl/test/__test_utils.jl:69
  Expression: length(unique(widths)) == 1
   Evaluated: 2 == 1
Stacktrace:
 [1] macro expansion
   @ [...]/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] testpanel(p::Panel, w::Int64, h::Nothing)
   @ Main[...]/Term.jl/test/__test_utils.jl:69
PANEL - FIT - measure: Test Failed at [...]/Term.jl/test/__test_utils.jl:69
  Expression: length(unique(widths)) == 1
   Evaluated: 2 == 1
Stacktrace:
 [1] macro expansion
   @ [...]/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
 [2] testpanel(p::Panel, w::Int64, h::Nothing)
   @ Main [...]/Term.jl/test/__test_utils.jl:69
Test Summary:              | Pass  Fail  Total
PANEL - FIT - measure  |  171     3    174
ERROR: LoadError: Some tests did not pass: 171 passed, 3 failed, 0 errored, 0 broken.
in expression starting at [...]/Term.jl/test/07_test_panel.jl:182
in expression starting at [...]/Term.jl/test/runtests.jl:43
ERROR: Package Term errored during testing
```

</details>

**Comment by FedeClaudi** [comment]
Hey thanks @johnnychen94 !
I've added a method to [`tprint`](https://github.com/FedeClaudi/Term.jl/blob/eb3e3b5f70e7562d87f92050a1550546314f2a01/src/markdown.jl#L263) to parse `MD` objects so that they get printed out nicely. When using Term's `repr` functionality [docstrings are parsed](https://github.com/FedeClaudi/Term.jl/blob/eb3e3b5f70e7562d87f92050a1550546314f2a01/src/repr.jl#L281) with the new functionality. 

So I'm not sure what you mean by this:
> default docstring print with Term's tprint

Also, regarding:
> , and would probably be troublesome when REPL docstring priting manner is changed when people indirectly load

The new repr functionality is optional, you need to run `install_term_repr()` like for the logging and stacktraces.

**Comment by FedeClaudi** [comment]
@t-bltg 

That's weird, the tests are passing on both of my machines and on the GH actions. Are you using a particularly narrow terminal window?

**Comment by t-bltg** [comment]
```bash
$ echo $LINES $COLUMNS
22 80
$ julia -e 'using Pkg; Pkg.test("Term")'  # OK
[...]

$ echo $LINES $COLUMNS
71 195
$ julia -e 'using Pkg; Pkg.test("Term")'  # KO
[...]
```

The tests should be independent on the size of the terminal.

**Comment by FedeClaudi** [comment]
They should already be. I've tried with different windows sizes and the emulated terminal for GH actions should be 80 columns wide. Let me see if I can replicate it. 

Wait from what you say, is it failing for the wider terminal?

**Comment by t-bltg** [comment]
> Wait from what you say, is it failing for the wider terminal?

Seems so:
```
$ echo $LINES $COLUMNS
22 167  # OK
22 195  # KO
```

**Comment by FedeClaudi** [comment]
> I see. For default docstring print I mean overring how help> map displays

Yeah no I won't be touching that. 

> but I think it's better to leave it as as an optional (opt-in) feature. Indeed, I wouldn't suggest it in the documentation

I'd say it's the dev's responsability to avoid doing that. I'd be for letting people know that this exists but adding a warning that if your code is going to be used by others you might want to avoid doing this, what do you think?

@t-bltg  thanks, I will look into this.

**Comment by johnnychen94** [comment]
> I'd be for letting people know that this exists but adding a warning that if your code is going to be used by others you might want to avoid doing this, what do you think?

Indeed, it's okay as long as it's an opt-in feature.
Furthermore, if our GSoC project progresses smoothly, then we'll eventually just move every overriding function provided in `install_term_repr` to the new package (say, TermDisplays) and just advertise `using TermDisplays` instead.

**Comment by lorenzoh** [comment]
> I see. That's a use case that I would like for Term to be able to handle, if you come up with a good solution perhaps you can contribute a PR?

For sure will open a PR if I get it working in a clean way 👍

**Comment by t-bltg** [comment]
> It remains to be determined what's causing tests failures on wide displays before merging into master.

I'm onto that.

**Comment by t-bltg** [comment]
`Panel("."^1500; fit=true)` is a simple bug reproducer.

**Comment by FedeClaudi** [comment]
@t-bltg this: https://github.com/FedeClaudi/Term.jl/pull/102#issuecomment-1153999960 is fixed now correct?

**Comment by t-bltg** [comment]
> @t-bltg this: https://github.com/FedeClaudi/Term.jl/pull/102#issuecomment-1153999960 is fixed now correct?

Yes, it's correctly rendered when `displaysize(stdout) == (22, 195)` which was the term size in the original bug. I've tested with alternative sizes (resizing my term window either very flat, very tall or squarish on a `1920x1080` display), and it seems to render correctly now.

**Comment by t-bltg** [comment]
@FedeClaudi, I forgot: would it be possible to export the symbol `grid` from the `Term.jl` module ?

**Comment by FedeClaudi** [comment]
sure I'll add it in Master

**Comment by t-bltg** [comment]
> sure I'll add it in Master

FYI, I've a PR pending for grid fixes, so it'd be great to wait a few hours before releasing `1.0.0`.

**Comment by FedeClaudi** [comment]
yeah I need to write the docs, it might take me a couple of days I'm a bit busy this week. But either way no rush, I can wait to release until you're ready too.

**Comment by FedeClaudi** [comment]
@t-bltg  docs for the new grid functionality you've contributed: https://fedeclaudi.github.io/Term.jl/dev/layout/grid/

**Comment by t-bltg** [comment]
Thanks for the hard work ! I'm also thinking of creating an exhaustive grid image (as what you've done with https://github.com/FedeClaudi/Term.jl/blob/master/readme.png) at the top of the `UnicodePlots.jl`s README.md, when `1.0.0` is released: `Term` + `UnicodePlots` = :heart: .

**Comment by t-bltg** [comment]
I'm wondering if we should shamelessly steal / adapt the `@layout` macro from `Plots.jl` (defined in `RecipesBase.jl`) in order to fine tune grid placements as in https://docs.juliaplots.org/latest/gallery/gaston/generated/gaston-ref55/#gaston_demo_55.

**Comment by FedeClaudi** [comment]
I originally wanted to have something like this: https://matplotlib.org/3.5.0/tutorials/provisional/mosaic.html#string-short-hand

for `Compositor` but found it very hard to implement. 

But yeah it  would be great to have!

---

> Also, we could maybe hide placeholders by default unless the whole grid consists of placeholders ...

yes

---
Also for `Compositor` I will add that you can give the elements' size in fraction of total width:
```julia
layout = :(A(.7, 1.0) * B(.3, 1.0))
```

will create a layout where `A` takes up 70% of the width.

**Comment by t-bltg** [comment]
Ha, thanks for the hints on `Compositor` (I'm still learning the internals of `Term.jl` :)) and mpl. I'll have a look at this within the day, I'm sure we can come up with something efficient, simple and robust.

**Pull request merged**
