### PR TITLE
no stdout in precomp

### PR DESCRIPTION
**Pull request by FedeClaudi**
Changed `_precompilation.jl` to avoid having to redirect `stdout` and to precompile more things.

### CODE REVIEW

**Comment by FedeClaudi** [comment]
@andreasnoack this should fix https://github.com/FedeClaudi/Term.jl/issues/190. 
I can't be sure because I never encountered that issue in the first place, but I've removed the need for `stdout` re-direct alltogether based on suggestions in: https://github.com/timholy/SnoopCompile.jl/issues/308#issuecomment-1373496879

Please not that this is being merged in `master` which currently holds code for the next big release of `Term.jl` for version `2.0` which introduces many new features and improvements. As such, it might be premature to grab the code from here as there's many not yet documented changes. However if you do want to do that, I'd be very happy to see how you like the new Term!

**Comment by andreasnoack** [comment]
Just tried this PR on the same machine where I experienced the deadlock and I can confirm that this PR fixes the issue.

**Comment by FedeClaudi** [comment]
awesome thanks for checking it out!

**Comment by andreasnoack** [comment]
It would actually be helpful if you could backport this fix to a `1.x` release. Otherwise it might take a while before we can precompile our package again.

**Comment by FedeClaudi** [comment]
Doing this here: https://github.com/FedeClaudi/Term.jl/pull/194/

I've removed the pre-compilation code alltogether. Once v2.0 drops I strongly recomend switching to it. There shouldn't be major breaking changes but lots of improvements and new functionality.

**Comment by FedeClaudi** [comment]
Please disregard the previous message and other notifications. It seems that I've messed up the commit history badly enough such that backporting those changes is actually not a great idea. 

If that works for you I can make a v2.0 release without the precompilation code now. Some of the new features are not fully finished yet but the rest of the code should be just the same as before, except the pre-compilation wouldn't bother you.

**Comment by andreasnoack** [comment]
Thanks for giving it a try. I'm fine with 2.0 but our project only pulls in Term as an indirect dependency so the upgrade is not under our direct control. We might be forced to stay of 1.x for a bit.

**Comment by FedeClaudi** [comment]
Got it. Sorry I couldn't be of more help, let me know if there's anything I can do!

**Comment by andreasnoack** [comment]
Took a closer a look. Usually, it's easier to make such a release from a dedicated release branch, i.e. I think it might be sufficient to make a branch similar to this one https://github.com/andreasnoack/Term.jl/tree/release-1.1 from my fork and then make a 1.1.1 from that one. (Or a similar `release-1.2` if you prefer 1.2.0.)

**Comment by FedeClaudi** [comment]
yeah so the problem is that I merged a bunch of commits for v2.0 into the master branch (not a great idea) so to grab code that doesn't have this and make a new release without the newer features I would have to revert to a previous commit: 4dda6677e3aa89d1b8edc12b2a7e05da53f1f05a

I can't figure out a way to do that in a way where I can then make a PR without having to grab the most recent code from master.

**Comment by andreasnoack** [comment]
> I can't figure out a way to do that in a way where I can then make a PR without having to grab the most recent code from master.

What I did, was to create the release branch, set it to v1.1.0, and revert the precompile commit, i.e.
```
git checkout -b release-1.1
git reset --hard v1.1.0
git revert e54f4d2a7a20c0a1698be1286bfa8590cbb87473
```
There is a very small conflict in the docs project but that's it. Then it could be possible to change the version on that branch and make the release from that branch and leave master as it is.

**Comment by FedeClaudi** [comment]
So I followed those steps and I have a branch with the new code, but I'm not sure how to release it without mergin the PR.  Normally I trigger the bot from an issue (https://github.com/FedeClaudi/Term.jl/issues/170) but I'm not sure how to tell it to pull it from a branch?

**Comment by andreasnoack** [comment]
You can trigger the release by commenting on the relevant commit, i.e. https://github.com/FedeClaudi/Term.jl/commit/18ede5119b14c4a2de68cc189b8ccd31230f0e5a

**Comment by FedeClaudi** [comment]
The new release should be coming out: https://github.com/FedeClaudi/Term.jl/issues/36#issuecomment-1387068215

I hope it fixes your issues!

**Pull request merged**
