### PR TITLE
Update Documenter configuration.

### PR DESCRIPTION
**Pull request by fredrikekre**
This updated the Documenter configuration to be a bit more "conventional". In particular, it removes the commited html files from the master branch, and updates the CI configuration to build and deploy automatically on pushes to master.

### CODE REVIEW

**Comment by fredrikekre** [comment]
I also updated the configuration for regular CI testing, but looks like you have disabled that action in the settings?

**Comment by fredrikekre** [comment]
That workflow seems very tedious IMO, are you manually syncing the code between the master and gh-pages branch then, or are you maintaining two different histories?

The proper workflow (at least what "everyone" is doing) is to do all development towards the `master` branch, code and documentation alike. With this workflow there is a single true source. CI and Documentation builds are triggered when you make a PR towards `master`, and when pushing/merging to `master` (at least with the configuration currently in this PR).

**Comment by FedeClaudi** [comment]
Okay, I see. 

I generally either work on the code for a while or on the docs for a while. So it's not much work to keep the histories separate. When I want to do docs I pull from master, when I'm done I do a PR into master. This is mostly to avoid having the commit history cluttered by docs-related commits. 
Also, in the future I will  do most development on dedicated branches until new features/fixes are ready for merging with master. 

I'll try the setup you're recommending though. I would like for term to be something where multiple people collaborate on the development so I want to align with the standard workflow practices.

Thank you for the help and explanations.

**Comment by fredrikekre** [comment]
I don't really think of documentation and code as separate things -- they are quite intertwined, and in particular when you consider docstrings, which are actually part of the julia files.

If you want the old workflow with iterative documentation updates you can keep an open pull request from a branch with doc changes, and you can rebase that on master when/if new changes are merged. You could then also enable preview buils (pass `push_preview = true` to `deploydocs`) and you can see the rendered documentation for the PR, but it won't be published until merged into master.

**Comment by fredrikekre** [comment]
To elaborate: Now that you merged this PR into `master` this [workflow](https://github.com/FedeClaudi/Term.jl/runs/5494558481?check_suite_focus=true) was triggered, which built and pushed [this commit](https://github.com/FedeClaudi/Term.jl/commit/9238c6bbe01fa5a134b6ee28f825a72a1212dbaf) to `gh-pages` branch automatically. So now the code and documentation on the `master` branch and in the HTML documentation are in sync automatically.

**Comment by FedeClaudi** [comment]
> So now the code and documentation on the master branch and in the HTML documentation are in sync automatically.

That's very nice actually. I guess it's worth those extra commits in the history (or maybe I should just do fewer typos when I write the docs 😄 ).

As you've seen I've triggered the release of the first version of `Term` (hoping that I can keep the name). I have some fairly substantial changes I want to make to how renderables are printed under the hood, but I think it's good enough to start having people play around with it and test it. Let me know if you end up using it and what your experience was like!

**Comment by FedeClaudi** [comment]
Hey @fredrikekre, sorry to bother you but I have a documenter-workflow question. 

Currently changes pushed to `master` result to changes to the `dev` version of the docs online, which is the only version shown. What's the best way to host multiple versions in the docs? Perhaps automatically have the docs for each released version of `Term` + one for the code being updated on the github repo?

**Comment by fredrikekre** [comment]
When [push tags](https://github.com/FedeClaudi/Term.jl/blob/765cf79e94b5a07bd1991dd75fcda44fdf3d049d/.github/workflows/documentation.yaml#L7) the document will build and push. Now, for some reason that didn't happen for your tags. You [already have tagbot setup](https://github.com/FedeClaudi/Term.jl/issues/36), so I am guessing you need to configure a deploy key. You would have to go through the steps here: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh and also enable this key for tagbot as described here: https://github.com/JuliaRegistries/TagBot#ssh-deploy-keys

**Pull request merged**
