### PR TITLE
fix segment width bug when the height were given

### PR DESCRIPTION
**Pull request by YongHee-Kim**
```julia
p = Panel(""; width = 5, height = 4)
julia> println(p)
```
*Before* 
image

*After*
image

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Awesome,  nice find thank you! I'll add it in and I've added tests to ensure this would be detected in the future.

**Comment by YongHee-Kim** [comment]
That was fast! I was just working on the test for this PR, but you've already merged it 😅 
https://github.com/YongHee-Kim/Term.jl/commit/9f990bddaabfa12678a8037f5205f23bb0d641db

**Comment by FedeClaudi** [comment]
Here: ed20b790987afb9547363d4edc1fc63c9c915412

Sorry I didn't realize you were still working on it, I should've checked first.
By the way you can open pull requests in Draft mode to prevent premature merging.

Thank you for helping with Term!

**Comment by YongHee-Kim** [comment]
No you don't have to check with me, It's bad habit of making a haste PR. Thanks for the tip. I should use draft mode in the future

**Comment by YongHee-Kim** [comment]
Absolutely! I think I will be using the `Term.jl` for my work. 

I'm on windows 10. If you need testing on windows, let me know I am happy to contribute. 

And thanks for the doc.

**Comment by FedeClaudi** [comment]
Awesome! 

I'm glad to hear you're planning to use it. Let me know how it goes. I've also opened `Discussions` up for generic questions/discussion. I don't know if you ever used `rich` in Python (which Term is based upon), but if there's something from `rich` you'd like to see implemented here let me know!

**Pull request merged**
